#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  local nm_vagrant_provider="$1"; shift
  local pth_box=

  case "$nm_vagrant_provider" in
    vmware|vmware_desktop|vmware_fusion)
      nm_vagrant_provider="vmware_fusion"
      ;;
    digitalocean|digital_ocean)
      nm_vagrant_provider="digital_ocean"
      ;;
    virtualbox|aws)
      true ;;
    *)
      echo ERROR: "Invalid virtualization type: $nm_vagrant_provider" 1>&2
      return 1
      ;;
  esac

  vagrant box remove --provider "$nm_vagrant_provider" ubuntu${1:+"-$1"}
}

source sub "$0" "$@"

