#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  # build it
  exec basebox build ubuntu "$@"
}

source sub "$BASH_SOURCE" "$@"
