#!/usr/bin/env bash

function main {
  local shome="${_basebox_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  case "${1:-}" in
    ovf|vmx|pvm)
      export BASEBOX_TYPE="$1"; shift
      ;;
  esac
  exec basebox build ubuntu "$@"
}

source sub "$BASH_SOURCE" "$@"
