#!/usr/bin/env bash

function main {
  local shome="${_basebox_ubuntu_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  cd "$shome"

  local nm_packer_builder=

  case "${VAGRANT_DEFAULT_PROVIDER:-}" in
    vmware*)    nm_packer_builder="vmware-${BASEBOX_TYPE:-iso}" ;;
    virtualbox) nm_packer_builder="virtualbox-${BASEBOX_TYPE:-iso}" ;;
    parallels)  nm_packer_builder="parallels-${BASEBOX_TYPE:-iso}" ;;
    docker)     nm_packer_builder='docker' ;;
    aws)        nm_packer_builder="amazon-ebs" ;;

    null) nm_packer_builder="null"
      if [[ -n "${1:-}" ]]; then
        export BASEBOX_REMOTE="${1:-}"
        shift
      fi
      ;;

    *)
      echo ERROR: "Invalid virtualization type: $VAGRANT_DEFAULT_PROVIDER" 1>&2
      return 1
      ;;
  esac

  if [[ -n "${1:-}" && "${nm_packer_builder}" != "docker" ]]; then
    export BASEBOX_NAME="${BASEBOX_NAME}-$1"
    shift
  fi

  local tmp_packer="$(mktemp -t XXXXXX)"
  cat "packer-${nm_packer_builder}.json" | jq \
    --arg provider "$VAGRANT_DEFAULT_PROVIDER" \
    --arg basebox_type "${BASEBOX_TYPE:+-${BASEBOX_TYPE}}" \
    '.provisioners[].scripts = [
        "script/first.sh",
        "script/update.sh",
        "script/sshd.sh",
        "script/network.sh",
        "script/pre-\($provider)\($basebox_type).sh",
        "script/\($provider).sh",
        "script/site.sh",
        "script/lxd.sh",
        "script/cleanup.sh",
        "script/last.sh" 
      ]' | tee "$tmp_packer" | jq --arg builder "$nm_packer_builder" '.builders = [ .builders[] | select(.type == $builder) ]'

  local tmp_options="$(mktemp -t XXXXXX)"
  jq -n \
    --arg provider "$VAGRANT_DEFAULT_PROVIDER" \
    --arg iso_path "$shome/iso" \
    --arg iso_dir "$shome" \
    '{  
        iso_path: $iso_path, 
        iso_dir: $iso_dir,
        provider: $provider
     }' | tee "$tmp_options"

  packer build${nm_packer_builder:+ -only="$nm_packer_builder"} -force -var-file "$tmp_options" "$tmp_packer"
  rm -f "$tmp_options" "$tmp_packer"
}

source sub "$BASH_SOURCE" "$@"
