#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local nm_region="${AWS_DEFAULT_REGION}"

  export BASEBOX_SUFFIX="-${nm_region}"

  # target aminame
  EC2_TARGET_AMI_NAME="packer-${nm_region}-$(date +%s)"
  export EC2_TARGET_AMI_NAME

  if [[ "$#" -gt 0 ]]; then
    AWS_TYPE="$1"; shift
  else
    AWS_TYPE="c4.large"
  fi
  export AWS_TYPE

  if [[ -z "${EC2_SOURCE_AMI:-}" ]]; then
    export EC2_SOURCE_AMI="$(aws ami)"
  fi

  # build it
  exec basebox build ubuntu "$@"
}

source sub "$BASH_SOURCE" "$@"
