#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  vagrant box list | tr '(,)' ' ' | sed "s#^#vagrant #"

  (set +f; ls -d "$shome/box"/*/*.box 2>&- || true) | sed "s#$shome/box/#box ubuntu #; s#/# #"
}

source sub "$0" "$@"
