#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  case "$VAGRANT_DEFAULT_PROVIDER" in
    *) vagrant box remove -f --provider "$VAGRANT_DEFAULT_PROVIDER" "${SOURCE_NAME}" ;;
  esac
}

source sub "$0" "$@"
