#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  local json_var='{}'

  local nm_builder
  local nm_provider
  local nm_region
  local nm_snapshot=
  local nm_vm="ubuntu1404"
  local fl_vagrant_key="false"
  local secret_key=
  local access_key=
  local image_id=
  local instance_type=

  if [[ "$#" == 0 ]]; then
    set -- virtualbox
  fi

  if [[ -n "${1:-}" ]]; then
    nm_builder="$1"; shift
  fi

  case "$nm_builder" in
    virtualbox|vmware|parallels)
      nm_provider="${nm_builder}"
      nm_builder="${nm_builder}-iso"
      fl_vagrant_key="true"
      true ;;

    aws)
      nm_provider="${nm_builder}"
      nm_builder="amazon-ebs"

      if [[ "$#" -gt 0 ]]; then
        nm_region="$1"; shift
      fi
      : ${nm_region:=${AWS_DEFAULT_REGION:-us-west-1}}

      nm_vm="${nm_vm}-${nm_region}"
      access_key="$AWS_ACCESS_KEY"
      secret_key="$AWS_SECRET_KEY"
      nm_snapshot="packer-${nm_region}-$(date +%s)"
      ;;

    digitalocean)
      nm_provider="${nm_builder}"
      
      if [[ "$#" -gt 0 ]]; then
        nm_region="$1"; shift
      fi

      : ${nm_region:=${DIGITALOCEAN_DEFAULT_REGION:-sfo1}}
      nm_vm="${nm_vm}-${nm_region}"
      secret_key="$DIGITALOCEAN_API_TOKEN"
      nm_snapshot="packer-${nm_region}-$(date +%s)"
      ;;

    "")
      true ;;

    "{"*)
      json_var="$nm_builder"
      nm_builder=
      ;;

    *)
      echo ERROR: "Invalid virtualization type: $nm_provider" 1>&2
      return 1
      ;;
  esac

  if [[ "$#" -gt 0 ]]; then
    image_id="$1"; shift
  fi

  if [[ "$#" -gt 0 ]]; then
    instance_type="$1"; shift
  fi

  case "${1:-}" in
    "{"*)
      json_var="$1"; shift
      ;;
  esac

  cd "$shome"
  local tmp_ubuntu="$(mktemp -t XXXXXX)"
  cat ubuntu.json | jq --arg provider "$nm_provider" \
                                         '.provisioners[].scripts = [
                                                      "script/first.sh",
                                                      "script/update.sh",
                                                      "script/vagrant.sh",
                                                      "script/sshd.sh",
                                                      "script/\($provider).sh",
                                                      "script/docker.sh",
                                                      "custom-script.sh",
                                                      "script/cleanup.sh",
                                                      "script/ubuntu.sh",
                                                      "script/last.sh" ]' | tee "$tmp_ubuntu"

  local tmp_options="$(mktemp -t XXXXXX)"
  jq -n --arg iso_path "$shome/iso" \
        --arg secret_key "$secret_key" \
        --arg access_key "$access_key" \
        --arg provider "$nm_provider" \
        --arg region "$nm_region" \
        --arg vm_name "$nm_vm" \
        --arg install_vagrant_key "$fl_vagrant_key" \
        --arg snapshot_name "$nm_snapshot" \
        --arg image_id "$image_id" \
        --arg instance_type "$instance_type" \
        --argfile ubuntu ubuntu1404.json '$ubuntu + { headless: "true", 
                                                      iso_path: $iso_path, 
                                                      ssh_username: "ubuntu",
                                                      docker: "true",
                                                      update: "true",
                                                      install_vagrant_key: $install_vagrant_key,
                                                      access_key: $access_key,
                                                      secret_key: $secret_key,
                                                      provider: $provider,
                                                      region: $region,
                                                      snapshot_name: $snapshot_name,
                                                      vm_name: $vm_name,
                                                      image_id: $image_id,
                                                      instance_type: $instance_type,
                                                      cpus: "2" }' | tee "$tmp_options"
  packer build${nm_builder:+ -only="$nm_builder"} -var-file "$tmp_options" "$tmp_ubuntu"
  rm -f "$tmp_options" "$tmp_ubuntu"
}

source sub "$0" "$@"
