#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  local nm_packer_builder=

  case "${VAGRANT_DEFAULT_PROVIDER:-}" in
    aws) nm_packer_builder="amazon-ebs" ;;

    *)
      echo ERROR: "Invalid virtualization type: $VAGRANT_DEFAULT_PROVIDER" 1>&2
      return 1
      ;;
  esac

  if [[ -n "${1:-}" ]]; then
    shift
  fi

  local tmp_packer="$(mktemp -t XXXXXX)"
  cat "packer-${nm_packer_builder}.json" | \
    jq \
      --argfile p "$shome/packer.json" \
      --argfile t "$shome/packer-xenial.json" \
      '.variables |= ({___packer: ""} + $p + {___ubuntu: ""} + $t + {___custom: ""} + .)' \
      | tee "$tmp_packer"

  export PACKER_TMP_DIR="${CACHE_DIR}/tmp/packer"
  mkdir -p "${PACKER_TMP_DIR}"
  packer build${nm_packer_builder:+ -only="$nm_packer_builder"} -force "$tmp_packer"
  rm -f "$tmp_packer"
}

source sub "$BASH_SOURCE" "$@"
