#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  local json_var='{}'

  local nm_only

  if [[ -n "${1:-}" ]]; then
    nm_only="$1"; shift
  fi

  case "$nm_only" in
    virtualbox|vmware|parallels)
      true ;;
    "")
      true ;;
    "{"*)
      json_var="$nm_only"
      nm_only=
      ;;
    *)
      echo ERROR: "Invalid virtualization type: $nm_only" 1>&2
      return 1
      ;;
  esac

  case "${1:-}" in
    "{"*)
      json_var="$1"; shift
      ;;
  esac

  local tmp_var="$(mktemp -t XXXXXX)"
  cd "$shome"
  cat ubuntu1404.json | jq '. + '"$json_var" | tee "$tmp_var"
  packer build${nm_only:+ -only="$nm_only-iso"} -var "iso_path=$shome/iso" -var-file="$tmp_var" ubuntu.json
  rm -f "$tmp_var"
}

source sub "$0" "$@"

