#!/usr/bin/env bash

if [[ -z "${BASEBOX_DOCKER_IMAGE:-}" ]]; then
  export BASEBOX_DOCKER_IMAGE='ubuntu:latest'
fi

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  local nm_packer_builder=
  local nm_provider=

  local nm_vm="ubuntu1404"

  case "$VAGRANT_DEFAULT_PROVIDER" in
    vmware_fusion|vmware_desktop)
      nm_provider="vmware_desktop"
      nm_packer_builder="vmware-${BASEBOX_TYPE:-iso}"
      ;;

    virtualbox)
      nm_provider="virtualbox"
      nm_packer_builder="virtualbox-${BASEBOX_TYPE:-iso}"
      ;;

    docker)
      nm_provider='docker'
      nm_packer_builder='docker'
      ;;

    aws)
      nm_provider="aws"
      nm_packer_builder="amazon-ebs"
      ;;

    *)
      echo ERROR: "Invalid virtualization type: $nm_provider" 1>&2
      return 1
      ;;
  esac

  local tmp_packer="$(mktemp -t XXXXXX)"
  cat "packer.json" | jq \
    --arg provider "$nm_provider" '.provisioners[].scripts = 
    [ "script/first.sh",
      "script/update.sh",
      "script/sshd.sh",
      "script/ubuntu.sh",
      "script/network.sh",
      "script/\($provider).sh",
      "script/site.sh",
      "script/cleanup.sh",
      "script/last.sh" 
      ]' | tee "$tmp_packer"

  local tmp_options="$(mktemp -t XXXXXX)"
  jq -n \
    --arg provider "$nm_provider" \
    --arg vm_name "$nm_vm" \
    --arg iso_path "$shome/iso" \
    --arg iso_dir "$shome" \
    '{  
        iso_path: $iso_path, 
        iso_dir: $iso_dir,
        provider: $provider,
        vm_name: $vm_name
     }' | tee "$tmp_options"

  packer build${nm_packer_builder:+ -only="$nm_packer_builder"} -var-file "$tmp_options" "$tmp_packer"
  rm -f "$tmp_options" "$tmp_packer"
}

env | grep BASEBOX

source sub "$BASH_SOURCE" "$@"
