#!/usr/bin/env bash

function main {
  export BASEBOX_TYPE='ovf'
  export BASEBOX_SUFFIX='ovf'

  if [[ -n "${1:-}" ]]; then
    BASEBOX_SUFFIX="-$1"; shift
  fi
  exec parity build ubuntu "$@"
}

source sub "$0" "$@"
