#!/usr/bin/env bash

function main {
  basebox build "$VAGRANT_DEFAULT_PROVIDER" "$@"
  basebox remove "$VAGRANT_DEFAULT_PROVIDER" 2>&1 >/dev/null
  basebox add "$VAGRANT_DEFAULT_PROVIDER"
}

main "$@"
