#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"
  
  echo "ERROR: building ubuntu media is not supported right now." 1>&2
  false
}

source sub "$BASH_SOURCE" "$@"
