#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"
  exec virtualbox build "$@"
}

source sub "$BASH_SOURCE" "$@"
