#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "${DISTRIB_ID}" in
    Darwin)
      brew unlink cdrtools || true
      brew install dvdrtools
      brew link dvdrtools
      ;;
    *)
      pkg ensure sysutils/cdrtools
      ;;
  esac
}

bootstrap
