#!/usr/bin/env bash

function bootstrap {
  local shome="${_basebox_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  pkg ensure sysutils/cdrtools
}

bootstrap
