#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ -x "$(which mkisofs 2>/dev/null || true)" ]]; then
    return 1
  fi

  return 0
}

bootstrap
