#!/usr/bin/env bash

function bootstrap {
  local shome="${_basebox_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ -x "$(which mkisofs 2>/dev/null || true)" ]]; then
    return 1
  fi

  return 0
}

bootstrap
